
 
version: "3"

services:
  mongo0:
    image: mongo:4.2
    command: /usr/bin/mongod --bind_ip_all --replSet rs0

  mongo1:
    image: mongo:4.2
    command: /usr/bin/mongod --bind_ip_all --replSet rs0

  mongo2:
    image: mongo:4.2
    command: /usr/bin/mongod --bind_ip_all --replSet rs0

  web_chat:
    build: web_chat
    image: elenpatrusheva/web_chat
    ports:
      - "80:5000"
    environment:
      MONGO: mongodb://mongo0,mongo1,mongo2/?replicaSet=rs0
